#connection: &connection
#  adapter: mysql2
#  encoding: utf8
#  database: etl_db
#  pool: 5
#  username: etl_user
#  password: pankotekbylchory
#  socket: /var/run/mysqld/mysqld.sock


connection: &connection
  adapter: postgresql
  encoding: utf8
  host: localhost
  pool: 5
  username: standard
  password: standard

development:
  <<: *connection
  database: etl_db

test:
  adapter: postgresql
  database: travis_ci_test