connection: &connection
  adapter: mysql2
  encoding: utf8
  database: etl_db
  pool: 5
  username: etl_user
  password: pankotekbylchory
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *connection

test: &test
  <<: *connection
  username: travis